apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - image: nakaderahul94/practice:httpd
        name: container-name
