apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mydep
  type: NodePort
status:
  loadBalancer: {}
