apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc # The name that matches the claimName in your Deployment
  namespace: dev # Make sure it's in the same namespace as your Deployment
spec:
  accessModes:
    - ReadWriteOnce # Must be compatible with the PV's access modes
  resources:
    requests:
      storage: 10Gi # The amount of storage you are requesting (should be <= PV's capacity)
